import React from 'react'

const About = () => {
   

  return (
    <div className='container' style={{marginTop:"120px"}}>
      <h1>About: </h1>
      <p className='my-3'>
      Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laudantium numquam quis aperiam illum veritatis atque consequatur voluptates, velit, nostrum quas eveniet quae error hic, laborum unde rem fugiat odit explicabo aliquid aliquam libero quo alias. Cupiditate repellat itaque, magni aliquam aut modi adipisci magnam consequuntur, quam, odio dolor! Sit dolore odio sed, ea, debitis molestias quam nesciunt facilis consequatur placeat amet laudantium tenetur natus laboriosam tempora voluptatum in minus ex fugiat quas asperiores ducimus! Delectus eos consequuntur harum, amet numquam nihil. Tempore esse sequi nihil odit laboriosam facilis accusantium quibusdam, totam dignissimos illum assumenda repellat obcaecati inventore, optio eius dicta!<br/>
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Suscipit iusto aliquam architecto ullam ad ea assumenda possimus eum mollitia. Est similique voluptates adipisci corporis in! Voluptatem fuga ratione dignissimos voluptatum optio dicta, officia reprehenderit earum? Quae ipsam maxime nisi esse consequuntur reprehenderit possimus laborum tempore, laboriosam, dolorem, ullam ratione! Delectus quos voluptates ut reprehenderit tempore ullam sint, fugit cumque dolorum facilis molestiae eius quo tempora modi atque laborum quibusdam fuga sed? Facere optio, ad soluta, nesciunt voluptas fugiat doloribus amet assumenda, tenetur quas repudiandae veniam placeat nemo omnis odio quaerat unde saepe accusamus alias debitis? Corrupti repellendus voluptatibus sunt eius modi exercitationem debitis at non distinctio cupiditate ut, provident necessitatibus deleniti excepturi eum suscipit consectetur explicabo, quaerat, quisquam deserunt. Sapiente, accusamus explicabo! Voluptatibus, rerum. Aliquid qui suscipit, explicabo incidunt omnis perspiciatis quam repudiandae voluptatibus id et architecto illo veritatis ex quae corporis, nesciunt dolore temporibus libero reiciendis, numquam non ut? Eveniet, dolore possimus, expedita ad voluptatem dolorem quos voluptates impedit vero molestias, quia a. Rem quas corrupti sed veniam. Eius aperiam iure iusto inventore illo voluptates odit nulla. Distinctio impedit totam dolor soluta dolore molestiae eaque adipisci, vitae accusamus facere, quibusdam voluptatibus animi dignissimos, repellendus corrupti earum blanditiis magnam expedita.<br/>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione a vitae repellat dolorum minus sapiente, vel repellendus adipisci molestias aliquam ex quia, quam itaque consequuntur sunt minima voluptatum ad iste deleniti. Veniam facere ducimus eius id? Vel eum beatae unde laboriosam officia quisquam voluptatem illo, harum dolorem cumque error aperiam quidem perspiciatis. Obcaecati officia eos blanditiis illum. Eum quo tempora rem nemo dolor quaerat architecto deleniti totam! Cupiditate voluptate doloremque deleniti velit totam iusto corrupti facilis saepe, atque quasi qui beatae autem possimus aut cum tenetur ad nihil ipsa ipsum sint maxime quaerat illum aperiam rem. Porro, asperiores doloribus? Perspiciatis quisquam cumque earum. Magnam, eius quidem. Quibusdam, libero! Est suscipit repudiandae voluptatem harum sed tempore, labore dolorum porro id? Excepturi voluptas nesciunt minus distinctio vel asperiores commodi itaque assumenda odio cumque labore suscipit provident quod ullam sed voluptates iste maiores voluptatum, obcaecati corporis. Vero similique optio beatae animi quis praesentium consequatur expedita ut natus possimus, dolorem odio, quasi ratione nam dignissimos veniam illum hic atque officia molestias commodi! Qui exercitationem esse vel dolores aspernatur dicta facere recusandae repellendus, officia placeat! Sed facere deleniti delectus porro est illo dolor debitis necessitatibus quaerat iusto mollitia, eius rem neque earum dolores vero nesciunt doloribus id facilis officiis vel non minima. Ut enim impedit perspiciatis? Nulla, in a. Voluptate impedit accusantium ab dolorum nam et delectus similique atque aut, minima est asperiores, doloribus provident nulla beatae fugit quos, praesentium dolore expedita! Repellat cum aliquid, beatae error minima in sapiente minus reprehenderit quidem corrupti, amet eius, sequi ex nam dicta. Odio mollitia dignissimos debitis praesentium error harum corrupti expedita ut sint. Nam id magni iure! Dolore eos quaerat iusto corporis quasi voluptatum? Unde quod ullam eum molestias aspernatur quidem consectetur cupiditate quas id saepe, fugit totam, quis soluta, reiciendis natus explicabo veritatis nihil animi! Doloremque.
      </p>
    </div>
  )
}

export default About
